HotelManager/HmanagerBackend/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'HmanagerBackend'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about', AboutUs.as_view(), name='about'),
    path('rooms', RoomsTemplate.as_view(), name='rooms'),
    path('gallery', Gallery.as_view(), name='gallery'),
    path('blog', BlogTemplates.as_view(), name='news'),
    path('contact', Contact.as_view(), name='contact'),
    path('reservation', ClientReservation.as_view(), name='reservation'),
    path('spa', Spa.as_view(), name='spa'),
    path('reservation_response', ReservationResponse.as_view(), name='resresponce'),
    path('admin/', admin.site.urls),
    path('register', register_Users),
    path('login', login_user),
    path('logout', logout_user),
    path('roomtype',roomtype_list),
    path('roomtype_details/<int:pk>/', roomtype_detail),
    path('status', status_list),
    path('reservation_list', reservation_list),
    path('room_list', room_list),
    path('bookings', booking),
    path('suggestions', suggestions_list),
    path('blogs_list', blogs_list)
  ]
urlpatterns = format_suffix_patterns(urlpatterns)

HotelManager/HotelManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HmanagerBackend.urls', namespace='HmanagerBackend'))
]

HotelManager/HmanagerBackend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import login, logout, authenticate


class User(AbstractUser):
    USERNAME_FIELD = 'username'


def upload_path(instance, static):
    return 'images/{filename}'.format(filename=static)


class RoomType(models.Model):
    room_type_id = models.IntegerField(primary_key=True)
    room_type_name = models.CharField(max_length=25)
    room_type_desc = models.CharField(max_length=250)
    room_type_pic = models.ImageField(blank=True, null=True, upload_to=upload_path)
    room_type_size = models.CharField(max_length=20)
    room_type_maxoc = models.IntegerField()
    room_type_cost = models.IntegerField()


class Status(models.Model):
    statusid = models.IntegerField()
    status = models.CharField(max_length=20)


class Reservation(models.Model):
    client_name = models.CharField(max_length=300, default='name')
    client_email = models.EmailField()
    client_phone = models.IntegerField()
    room_type_id = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    client_checkin = models.DateField()
    client_checkout = models.DateField()
    no_of_adults = models.IntegerField(default=1)
    no_of_children = models.IntegerField(default=0)
    statusid = models.ForeignKey(Status, on_delete=models.CASCADE)

    # objects = models.Manager()


class Room(models.Model):
    room_number = models.IntegerField(primary_key=True)
    room_type_id = models.ForeignKey(RoomType, related_name='rooms',on_delete=models.CASCADE)
    statusid = models.ForeignKey(Status, on_delete=models.CASCADE)


class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    client_name = models.CharField(max_length=300, default='widambe')
    client_phone = models.IntegerField()
    client_email = models.EmailField()
    checkin = models.DateField()
    checkout = models.DateField()
    no_of_guests = models.IntegerField()
    no_of_children = models.IntegerField()
    room_payment = models.IntegerField(default=200000)
    room_number = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Blog(models.Model):
    blog_id = models.AutoField(primary_key=True)
    blog_title = models.CharField(max_length=200)
    blog_post = models.ImageField()
    blog_subtitle = models.CharField(max_length=200)
    blog_content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateField()
    blog_likes = models.IntegerField()


class BlogComment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    blog_id = models.ForeignKey(Blog,related_name='comments', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_owner = models.CharField(max_length=60)


class Suggestions(models.Model):
    suggestion_id = models.IntegerField()
    client_email = models.EmailField()
    suggestion = models.TextField()

HotelManager/HmanagerBackend/views.py
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from .models import *
from .serializers import *
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "index.html"


class ClientReservation(TemplateView):
    template_name = "appoinment.html"
    # def get(self, request):
    #     data = RoomType.objects.
    def post(self, request):
        if request.method == 'POST':
            name = request.POST['clientname']
            checkin = request.POST['checkin']
            checkout = request.POST['checkout']
            roomtype = request.POST['roomtype']
            no_adults = request.POST['adults']
            no_children = request.POST['children']
            client_email = request.POST['email']
            client_phone = request.POST['phone']
            print(name, checkout, client_email, client_phone, roomtype)
            rt_id = RoomType.objects.get(room_type_name=roomtype)
            stat_id = Status.objects.get(id=1)
            reservation_instance = Reservation(client_name=name, client_email=client_email, client_phone=client_phone,
                                               room_type_id=rt_id, client_checkin=checkin, client_checkout=checkout,
                                               no_of_adults=no_adults, no_of_children=no_children, statusid=stat_id)
            reservation_instance.save()
            print(reservation_instance)

            return render(request, 'confirmation.html')



class ReservationResponse(TemplateView):
    template_name = "confirmation.html"


class Contact(TemplateView):
    template_name = "contact.html"


class AboutUs(TemplateView):
    template_name = "about.html"


class RoomsTemplate(TemplateView):
    template_name = "rooms.html"


class Gallery(TemplateView):
    template_name = "gallery.html"


class BlogTemplates(TemplateView):
    template_name = "news.html"


class Spa(TemplateView):
    template_name = "dinning.html"


@api_view(['POST','GET'])
def roomtype_list(request):
    '''
    lists all the available room types and adds new types
    '''
    if request.method == 'GET':
        roomtypes = RoomType.objects.all()
        roomtypes_set = RoomTypeSerializer(roomtypes, many=True)
        return Response(roomtypes_set.data)

    elif request.method == 'POST':
        serializer = RoomTypeSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def roomtype_detail(request, pk):
    """
    Retrieve, update or delete a code snippet.
    """
    try:
        roomtype = RoomType.objects.get(pk=pk)
    except RoomType.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = RoomTypeSerializer(roomtype)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = RoomTypeSerializer(roomtype, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        roomtype.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['POST'])
@permission_classes({AllowAny})
def register_Users(request):
    serializer = UserSerializer(data=request.data)
    if serializer.is_valid():
        print('hey i reach here')
        account = serializer.save()
        account.is_active = True
        account.save()
        return Response({'sms': 'successful register'})

    data = serializer.errors

    return Response(data)


# {
#     "username":"Michael",
#     "email":"michaelcyril71@gmail.com",
#     "password":"123",
# }


@api_view(['POST'])
@permission_classes({AllowAny})
def login_user(request):
    username = request.data['username']
    password = request.data['password']
    user = authenticate(username=username, password=password)
    # if user:
    print(user)
    if user is not None:
        login(request, user)
        return Response({'message': 'login successful'})
    return Response({'sms': 'failed'})


# return render(request, 'login.html')
# {
#  "username":"widambe",
# "password":"widambe30"
#  }

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def logout_user(request):
    logout(request)
    return Response({'message': 'successfull logout'})


@api_view(['POST','GET'])
def status_list(request):
    '''
    lists all the available room types and adds new types
    '''
    if request.method == 'GET':
        statuses = Status.objects.all()
        status_set = StatusSerializer(statuses, many=True)
        return Response(status_set.data)

    elif request.method == 'POST':
        serializer = StatusSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['POST','GET'])
def reservation_list(request):
    if request.method == 'GET':
        reservations = Reservation.objects.all()
        reservation_set = ReservationSerializer(reservations, many=True)
        return Response(reservation_set.data)
    elif request.method == 'POST':
        serializer = ReservationSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST', 'GET'])
def room_list(request):
    if request.method == 'GET':
        rooms = Room.objects.all()
        room_set = RoomSerializer(rooms, many=True)
        return Response(room_set.data)
    elif request.method == 'POST':
        serializer = RoomSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST', 'GET'])
def booking(request):
    if request.method == 'GET':
        bookings = Booking.objects.all()
        booking_set = BookingSerializer(bookings, many=True)
        return Response(booking_set.data)
    elif request.method == 'POST':
        serializer = BookingSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST', 'GET'])
def suggestions_list(request):
    if request.method == 'GET':
        suggestions = Suggestions.objects.all()
        suggestions_set = SuggestionsSerializer(suggestions, many=True)
        return Response(suggestions_set.data)
    elif request.method == 'POST':
        serializer = SuggestionsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST', 'GET'])
def blogs_list(request):
    if request.method == 'GET':
        blogposts = Blog.objects.all()
        blogpost_set = BlogSerializer(blogposts, many=True)
        return Response(blogpost_set.data)
    elif request.method == 'POST':
        serializer = BlogSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

HotelManager/HmanagerBackend/templates/appoinment.html
{% include "base.html" %}
	<!--end-->
	 <div id="myCarousel1" class="carousel slide" data-ride="carousel"> 
		<!-- Indicators -->

		<ol class="carousel-indicators">
			<li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel1" data-slide-to="1"></li>
			<li data-target="#myCarousel1" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner">
			<div class="item active"> <img src="images/banner.png" style="width:100%; height: 500px" alt="First slide">
				<div class="carousel-caption">
					<h1>GrolyHotel<br>Make A Reservation</h1>
				</div>
			</div>
			<div class="item"> <img src="images/banner2.png" style="width:100%; height: 500px" alt="Second slide">
				<div class="carousel-caption">
					<h1>GrolyHotel<br>Make A Reservation</h1>
				</div>
			</div>
			<div class="item"> <img src="images/banner3.png" style="width:100%; height: 500px" alt="Third slide">
				<div class="carousel-caption">
					<h1>GrolyHotel<br>Make A Reservation</h1>
				</div>
			</div>

		</div>
		<a class="left carousel-control" href="#myCarousel1" data-slide="prev"> <img src="images/icons/left-arrow.png" onmouseover="this.src = 'images/icons/left-arrow-hover.png'" onmouseout="this.src = 'images/icons/left-arrow.png'" alt="left"></a>
		<a class="right carousel-control" href="#myCarousel1" data-slide="next"><img src="images/icons/right-arrow.png" onmouseover="this.src = 'images/icons/right-arrow-hover.png'" onmouseout="this.src = 'images/icons/right-arrow.png'" alt="left"></a>

	</div>
	<div class="clearfix"></div>
    <section class="gallery-block gallery-front">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
					<div class="gallery-image">
						<img class="img-responsive" src="images/room1.png">
						<div class="overlay">
							<a class="info pop example-image-link img-responsive" href="images/room1.png" data-lightbox="example-1"><i class="fa fa-search" aria-hidden="true"></i></a>
							<p><a>delux room</a></p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
					<div class="gallery-image">
						<img class="img-responsive" src="images/room2.png">
						<div class="overlay">
							<a class="info pop example-image-link img-responsive" href="images/room2.png" data-lightbox="example-1"><i class="fa fa-search" aria-hidden="true"></i></a>
							<p><a>delux room</a></p>
						</div>
						<h3>delux room
							Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium aliquid facere ipsum itaque veniam iure! Deleniti harum, assumenda fugit rerum omnis nisi dicta excepturi esse, eveniet maxime quasi odit ipsam.
						</h3>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
					<div class="gallery-image">
						<img class="img-responsive" src="images/room3.png">
						<div class="overlay">
							<a class="info pop example-image-link img-responsive" href="images/room3.png" data-lightbox="example-1"><i class="fa fa-search" aria-hidden="true"></i></a>
							<p><a>delux room</a></p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
					<div class="gallery-image">
						<img class="img-responsive" src="images/room4.png">
						<div class="overlay">
							<a class="info pop example-image-link img-responsive" href="images/room4.png" data-lightbox="example-1"><i class="fa fa-search" aria-hidden="true"></i></a>
							<p><a>delux room</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<div id="booking" class="section">
		<div class="section-center">
			<div class="container">
				<div class="row">
					<div class="booking-form">
						<div class="form-header">
							<h1>Make your reservation</h1>
						</div>
						<form action="{% url 'HmanagerBackend:reservation' %}" method="post">
							{% csrf_token %}
							<div class="form-group">
								<input class="form-control" type="text" placeholder="name..." name="clientname">
								<label class="form-label" for="your_name">Name</label>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input class="form-control" type="date" name="checkin" required>
										<label class="form-label" for="checkin">Check In</label>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<input class="form-control" type="date" name="checkout" required>
										<label class="form-label" for="checkout">Check out</label>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-4">
									<div class="form-group">
										<select class="form-control" name="roomtype" required>
											<option value="" selected hidden>room type</option>
											<option>suite</option>
											<option>double</option>
											<option>Deluxe</option>
										</select>
										<span class="select-arrow"></span>
										<label class="form-label" for="room_type_name">Rooms</label>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
											<input class="form-control" type="number" name="adults" required>
										<label class="form-label" for="no_of_adults">Adults</label>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
								     <input class="form-control" type="number" name="children" required>
										<label class="form-label" for="no_of_children">Children</label>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input class="form-control" type="email" name="email" placeholder="Enter your Email">
										<label class="form-label" for="client_email">Email</label>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<input class="form-control" type="tel"  name="phone" placeholder="Enter you Phone">
										<label class="form-label" for="client_phone">Phone</label>
									</div>
								</div>
							</div>
							<div class="form-btn">
								<button class="submit-btn" type="submit">Book Now</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

<!---footer--->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-6 col-xs-12 width-set-50">
				<div class="footer-details">
					<h4>Get in touch</h4>
					<ul class="list-unstyled footer-contact-list">
						<li>
							<i class="fa fa-map-marker fa-lg"></i>
							<p>701 Old York Drive Richmond USA.</p>
						</li>
						<li>
							<i class="fa fa-phone fa-lg"></i>
							<p><a href="tel:+1-202-555-0100"> +1-202-555-0100</a></p>
						</li>
						<li>
							<i class="fa fa-envelope-o fa-lg"></i>
							<p><a href="mailto:demo@info.com"> demo@info.com</a></p>
						</li>
					</ul>
					<div class="footer-social-icon">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>                           
						<a href="#"><i class="fa fa-instagram"></i></a>
						<a href="#"><i class="fa fa-google-plus"></i></a>
						<a href="#"><i class="fa fa-youtube-play"></i></a>
					</div>
					<div class="input-group" id="subscribe">
						<input type="text" class="form-control subscribe-box" value="" name="subscribe" placeholder="EMAIL ID">
						<span class="input-group-btn">
							<button type="button" class="btn subscribe-button"><i class="fa fa-paper-plane fa-lg"></i></button>
						</span>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 width-50 width-set-50">
				<div class="footer-details">
					<h4>explore</h4>
					<ul class="list-unstyled footer-links">
						<li class="active"><a>Home</a></li>
						<li><a href="about.html">About</a></li>
						<li><a href="rooms.html">Rooms</a></li>
						<li><a href="gallery.html">Gallery</a></li>
						<li><a href="#">Dinning</a></li>
						<li> <a href="news.html">News</a></li>
						<li> <a href="contact.html">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-6 col-sm-12 col-xs-12">
				<div class="footer-details">
					<h4>Now On Instagram</h4>
					<div class="row">
						<div class="instagram-images">
							<div id="instafeed"></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="copyright">
			&copy; 2017 All right reserved. Designed by <a href="http://www.themevault.net/" target="_blank">ThemeVault.</a>
		</div>

	</div>
</footer>

<!--back to top--->
<a style="display: none;" href="javascript:void(0);" class="scrollTop back-to-top" id="back-to-top">
	<span><i aria-hidden="true" class="fa fa-angle-up fa-lg"></i></span>
	<span>Top</span>
</a>

  </body>
  </html>

HotelManager/HmanagerBackend/templates/base.html
<!DOCTYPE html>
<html lang="zxx">
	<head>
            {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="images/icons/favicon.png"/>
        <title>Groly-Hotel</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Custom styles for this template -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'fonts/antonio-exotic/stylesheet.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/booking.css' %}">
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/lightbox-plus-jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/instafeed.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
    </head>
    <body>
        <div id="page">
            <!---header top---->
            <div class="top-header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <!--                            <a href="#"> </a>
                                 <div class="info-block"><i class="fa fa-map"></i>701 Old York Drive Richmond USA.</div>-->
                        </div>
                        <div class="col-md-6">
                            <div class="social-grid">
                                <ul class="list-unstyled text-right">
                                    <li><a><i class="fa fa-facebook"></i></a></li>
                                    <li><a><i class="fa fa-twitter"></i></a></li>
                                    <li><a><i class="fa fa-linkedin"></i></a></li>
                                    <li><a><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--header--->
            <header class="header-container">
                <div class="container">
                    <div class="top-row">
                        <div class="row">
                            <div class="col-md-2 col-sm-6 col-xs-6">
                                <div id="logo">
                                    <!--<a href="index.html"><img src="images/logo.png" alt="logo"></a>-->
                                    <a href="{% url 'HmanagerBackend:home' %}"><span>vacay</span>home</a>
                                </div>
                            </div>
                            <div class="col-sm-6 visible-sm">
                                <div class="text-right"><button type="button" class="book-now-btn">Book Now</button></div>
                            </div>
                            <div class="col-md-8 col-sm-12 col-xs-12 remove-padd">
                                <nav class="navbar navbar-default">
                                    <div class="navbar-header page-scroll">
                                        <button data-target=".navbar-ex1-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>

                                    </div>
                                    <div class="collapse navigation navbar-collapse navbar-ex1-collapse remove-space">
                                        <ul class="list-unstyled nav1 cl-effect-10 active">
                                            <li><a  data-hover="Home"  href="{% url 'HmanagerBackend:home' %}"><span>Home</span></a></li>
                                            <li><a data-hover="About"  href="{% url 'HmanagerBackend:about' %}"><span>About</span></a></li>
                                            <li><a data-hover="Rooms"  href="{% url 'HmanagerBackend:rooms' %}"><span>Rooms</span></a></li>
                                            <li><a data-hover="Gallery"  href="{% url 'HmanagerBackend:gallery' %}"><span>Gallery</span></a></li>
                                            <li><a data-hover="Dinning" href="{% url 'HmanagerBackend:spa' %}"><span>Dinning</span></a></li>
                                            <li><a data-hover="News" href="{% url 'HmanagerBackend:news' %}"><span>News</span></a></li>
                                            <li><a data-hover="Contact Us" href="{% url 'HmanagerBackend:contact' %}"><span>contact Us</span></a></li>
                                        </ul>

                                    </div>
                                </nav>
                            </div>
                            <div class="col-md-2  col-sm-4 col-xs-12 hidden-sm">
                                <div class="text-right"><button type="button" class="book-now-btn"><a href="{% url 'HmanagerBackend:reservation' %}"><span>Booknow</span></a></button></div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>